/** Declaration file generated by dts-gen */
declare module 'last-fm' {

    export = last_fm;

    declare class last_fm {
        constructor(...args: any[]);

        albumInfo(...args: any[]): void;

        albumSearch(...args: any[]): void;

        albumTopTags(...args: any[]): void;

        artistCorrection(...args: any[]): void;

        artistInfo(...args: any[]): void;

        artistSearch(...args: any[]): void;

        artistSimilar(...args: any[]): void;

        artistTopAlbums(...args: any[]): void;

        artistTopTags(...args: any[]): void;

        artistTopTracks(...args: any[]): void;

        chartTopArtists(...args: any[]): void;

        chartTopTags(...args: any[]): void;

        chartTopTracks(...args: any[]): void;

        geoTopArtists(...args: any[]): void;

        geoTopTracks(...args: any[]): void;

        search(...args: any[]): void;

        tagInfo(...args: any[]): void;

        tagSimilar(...args: any[]): void;

        tagTopAlbums(...args: any[]): void;

        tagTopArtists(...args: any[]): void;

        tagTopTags(...args: any[]): void;

        tagTopTracks(...args: any[]): void;

        trackCorrection(...args: any[]): void;

        trackInfo(...args: any[]): void;

        trackSearch(...args: any[]): void;

        trackSimilar(...args: any[]): void;

        trackTopTags(...args: any[]): void;

    }

}